### ISSUE TITLE
Geolocalizzazione Fiera del Mediterraneo a Palermo

### ISSUE THREAD

**Issue by gbvitrano** [emergenzeHack/ukrainehelp.emergenzehack.info#107]
Buongiorno, c'è un piccolo errore nella geolocalizzazione della Fiera del Mediterraneo a Palermo,  queste sono le cood. giuste 
`38.14539, 13.35615`
![image](https://user-images.githubusercontent.com/20488693/161009960-3f22f5be-f9ee-49f9-a672-e7c2319b854c.png)

questa è sbagliata
![2022-03-31_09h58_26](https://user-images.githubusercontent.com/20488693/161009203-474d1e8d-c3c9-4b53-ab05-bbcd5da2de4c.png)

**Priorità**: bassa

## Risolto?

* [ ] Ho verificato che il problema è stato risolto

**Comment by iltempe** [comment]
scusate @cristigalas @favoeva si può sistemare? grazie

**Comment by cristigalas** [comment]
@iltempe volentieri ma come si fa? Lo avevo già detto a @abonte che non mi azzardo ad intervenire a mano sulla segnalazione per inserire le nuove coordinate. Non saprei dove metterle 🥺

**Comment by abonte** [comment]
Bisogna guardare su Nominatim se si riescono a ricavare i nuovi valore di tutti i campi dell'oggetto address.

```
address:
    place_id: 283839135
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 39295
    boundingbox:
    - '37.5393034'
    - '38.7206781'
    - '12.9287426'
    - '14.2943904'
    lat: '37.8819449'
    lon: '13.609543686318478'
    display_name: Palermo, Sicilia, Italia
    class: boundary
    type: administrative
    importance: 0.5763208078597727
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      county: Palermo
      state: Sicilia
      country: Italia
      country_code: it
```
